### ISSUE TITLE
Unable build with React Native.

### ISSUE THREAD

**Issue by azuzi** [datatrans/android-sdk#1]
I'm trying to use the Android sdk with a react native project, but during compilation, this gives the following error.

`> Task :app:processDebugResources FAILED
165 actionable tasks: 4 executed, 161 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_activity.xml:10: AAPT: error: attribute layout_constraintBottom_toBottomOf (aka ch.mysponsor.android:layout_constraintBottom_toBottomOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_activity.xml:10: AAPT: error: attribute layout_constraintEnd_toEndOf (aka ch.mysponsor.android:layout_constraintEnd_toEndOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_activity.xml:10: AAPT: error: attribute layout_constraintStart_toStartOf (aka ch.mysponsor.android:layout_constraintStart_toStartOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_activity.xml:10: AAPT: error: attribute layout_constraintWidth_max (aka ch.mysponsor.android:layout_constraintWidth_max) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_content.xml:5: AAPT: error: attribute layout_constraintTop_toTopOf (aka ch.mysponsor.android:layout_constraintTop_toTopOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_content.xml:12: AAPT: error: attribute layout_constrainedHeight (aka ch.mysponsor.android:layout_constrainedHeight) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_content.xml:12: AAPT: error: attribute layout_constraintBottom_toTopOf (aka ch.mysponsor.android:layout_constraintBottom_toTopOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_content.xml:12: AAPT: error: attribute layout_constraintTop_toBottomOf (aka ch.mysponsor.android:layout_constraintTop_toBottomOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_content.xml:20: AAPT: error: attribute layout_constraintBottom_toBottomOf (aka ch.mysponsor.android:layout_constraintBottom_toBottomOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_content.xml:20: AAPT: error: attribute layout_constraintTop_toTopOf (aka ch.mysponsor.android:layout_constraintTop_toTopOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_content.xml:28: AAPT: error: attribute layout_constraintBottom_toTopOf (aka ch.mysponsor.android:layout_constraintBottom_toTopOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_bottom_sheet_content.xml:35: AAPT: error: attribute layout_constraintBottom_toBottomOf (aka ch.mysponsor.android:layout_constraintBottom_toBottomOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_credit_card_date_cvv_fragment.xml:10: AAPT: error: attribute layout_constraintEnd_toEndOf (aka ch.mysponsor.android:layout_constraintEnd_toEndOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_credit_card_date_cvv_fragment.xml:10: AAPT: error: attribute layout_constraintStart_toStartOf (aka ch.mysponsor.android:layout_constraintStart_toStartOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_credit_card_date_cvv_fragment.xml:10: AAPT: error: attribute layout_constraintTop_toTopOf (aka ch.mysponsor.android:layout_constraintTop_toTopOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_credit_card_date_cvv_fragment.xml:35: AAPT: error: attribute flow_horizontalAlign (aka ch.mysponsor.android:flow_horizontalAlign) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_credit_card_date_cvv_fragment.xml:80: AAPT: error: attribute layout_constraintBottom_toBottomOf (aka ch.mysponsor.android:layout_constraintBottom_toBottomOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_credit_card_date_cvv_fragment.xml:80: AAPT: error: attribute layout_constraintEnd_toEndOf (aka ch.mysponsor.android:layout_constraintEnd_toEndOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_credit_card_date_cvv_fragment.xml:80: AAPT: error: attribute layout_constraintStart_toStartOf (aka ch.mysponsor.android:layout_constraintStart_toStartOf) not found.
         
     /home/azim/.gradle/caches/transforms-2/files-2.1/28dce21dcecee832fc7e0d142cd899ae/jetified-datatrans-android-1.0.0/res/layout/dtpl_credit_card_date_cvv_fragment.xml:80: AAPT: error: attribute layout_constraintTop_toBottomOf (aka ch.mysponsor.android:layout_constraintTop_toBottomOf) not found.`

**Comment by richiehug** [comment]
Hey @azuzi - checking with the team. Will get back to you asap.

**Comment by richiehug** [comment]
@azuzi It seems your bug can only be reproduced in combination with React Native. Can't reproduce it on our end. If your issue persists, please reach out to support@datatrans.ch including a sample native app where your bug can be reproduced and we'll take it from there.

PS: We don't officially support React Native integrations. But I'm happy to consider adding your suggestions to our docs if you happen to find a solution for your React Native issue.

**Comment by kantorm** [comment]
@azuzi have you find the solution for this issue?

**Comment by azuzi** [comment]
@kantorm yes, we have solution but only working in gradle 3.x.x
