### ISSUE TITLE
[3.1.1] Unable to match the desired swap behavior

### ISSUE THREAD

**Issue by AmirSalahY** [datatrans/android-sdk#11]
When triggering the Transaction function with the token
it shows me this error
`Unable to match the desired swap behavior.`

<img width="321" alt="image" src="https://github.com/datatrans/android-sdk/assets/10741932/192161eb-0879-463c-be69-5e6fb41cf221">

**expectations:** 
to show the forms correctly

**Comment by richiehug** [comment]
Hey @AmirSalahY - can you please share a `mobileToken` and how you invoke the SDK?

**Comment by bacherma** [comment]
Hi @AmirSalahY, thanks for the report. However, we need way more context to figure out what could cause your issue and to reproduce it. OS, simulator or device, hardware, dev environment, frameworks & tools used, what are you doing in the code exactly, and so on.

**Comment by AmirSalahY** [comment]
`package com.reactnativedatatrans;
import android.app.Activity;
import android.util.Log;

import androidx.annotation.NonNull;

import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import java.util.Map;
import java.util.HashMap;

import ch.datatrans.payment.api.Transaction;
import ch.datatrans.payment.api.TransactionListener;
import ch.datatrans.payment.api.TransactionRegistry;
import ch.datatrans.payment.api.TransactionSuccess;
import ch.datatrans.payment.exception.TransactionException;

public class DatatransModule extends ReactContextBaseJavaModule implements TransactionListener {
    DatatransModule(ReactApplicationContext context) {
        super(context);
    }

    @NonNull
    @Override
    public String getName() {
        return "DatatransModule";
    }

    @ReactMethod
    public void logData(String name, String text) {
        Log.d("CalendarModule", "Create event called with name: " + name
                + " and location: " + text);
    }

    @ReactMethod
    public void initDatatrans(){
        Activity activity = getCurrentActivity();

        Transaction transaction = new Transaction("8b26a173484a7fbfe82f7009d6e859f7033352e5efe77416");
        transaction.setListener(this); // this refers to Android's Activity
        transaction.getOptions().setTesting(true);
        transaction.getOptions().setUseCertificatePinning(true);
        TransactionRegistry.INSTANCE.startTransaction(activity, transaction);
    }

    @Override
    public void onTransactionCancel() {

    }

    @Override
    public void onTransactionError(@NonNull TransactionException e) {

    }

    @Override
    public void onTransactionSuccess(@NonNull TransactionSuccess transactionSuccess) {

    }
}`

**Comment by AmirSalahY** [comment]
OR THIS
```
package com.reactnativedatatrans;
import android.app.Activity;
import android.util.Log;

import androidx.annotation.NonNull;

import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.WritableMap;

import ch.datatrans.payment.api.Transaction;
import ch.datatrans.payment.api.TransactionListener;
import ch.datatrans.payment.api.TransactionRegistry;
import ch.datatrans.payment.api.TransactionSuccess;
import ch.datatrans.payment.api.tokenization.PCIPCardInfo;
import ch.datatrans.payment.exception.TransactionException;
import ch.datatrans.payment.paymentmethods.Card;
import ch.datatrans.payment.paymentmethods.CardExpiryDate;
import ch.datatrans.payment.paymentmethods.PaymentMethodType;

public class DatatransModule extends ReactContextBaseJavaModule implements TransactionListener {
    DatatransModule(ReactApplicationContext context) {
        super(context);
    }
    private static final String E_ACTIVITY_DOES_NOT_EXIST = "E_ACTIVITY_DOES_NOT_EXIST";
    private Promise mPromise;

    @NonNull
    @Override
    public String getName() {
        return "DatatransModule";
    }

    @ReactMethod
    public void logData(String name, String text) {
        Log.d("CalendarModule", "Create event called with name: " + name
                + " and location: " + text);
    }

    @ReactMethod
    public void initDatatrans( final Promise promise){
        Activity activity = getCurrentActivity();
        if (activity == null) {
            WritableMap map = Arguments.createMap();
            map.putString("message", "Activity doesn't exist");
            consumeCallback(E_ACTIVITY_DOES_NOT_EXIST, map);
            return;
        }

        try {
            Transaction transaction = new Transaction("8b26a173484a7fbfe82f7009d6e859f7033352e5efe77416");
            transaction.setListener(this); // this refers to Android's Activity
            transaction.getOptions().setTesting(true);
            transaction.getOptions().setUseCertificatePinning(true);
            TransactionRegistry.INSTANCE.startTransaction(activity, transaction);
        }catch (Exception e) {

            mPromise.reject(e);
        }
//        return transaction;
    }

    @Override
    public void onTransactionCancel() {
        Log.d("canceled","onTransaction Canceled");
    }

    @Override
    public void onTransactionError(@NonNull TransactionException e) {
        Log.d("error","onTransaction error");
    }

    @Override
    public void onTransactionSuccess(@NonNull TransactionSuccess transactionSuccess) {
        Log.d("success","onTransaction succeed ");
    }

    private void consumeCallback(String type, WritableMap map) {
        if (mPromise != null) {
            map.putString("type", type);
            map.putString("provider", "ct-datatrans");

            mPromise.resolve(map);
            mPromise = null;
        }
    }
}
```

**Comment by luiscosta** [comment]
Hello @AmirSalahY,

I will need the full stacktrace.

The `8b26a173484a7fbfe82f7009d6e859f7033352e5efe77416` mobile token you are not setting the appCallbackScheme. When you use PAP you must define one.

Can you also tell me which is your appCallbackScheme? Note that it must comply with RFC 3986.

**Comment by AmirSalahY** [comment]
Thanks @luiscosta for your answer
is there any reference u suggest to create one for android and one for ios?

**Comment by luiscosta** [comment]
Hello again @AmirSalahY,

If you are asking about the reference for the RFC 3986, you can follow the documentation at: 
https://datatracker.ietf.org/doc/html/rfc3986#autoid-18

**Comment by bacherma** [comment]
@AmirSalahY, can you please post the full stack trace? We suspect there may be a configuration error as @luiscosta mentioned. The fact that the dialog is shown means the SDK is invoked, so the React Native bridge is working. We need to see where that error is thrown.

**Comment by AmirSalahY** [comment]
which stack exactly do u need

**Comment by AmirSalahY** [comment]
sorry for being late

` 11:09:04.474 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrora.a.a.h.a$a.invokeSuspend(SourceFile:164)
2023-06-25 11:09:04.474 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorkotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-06-25 11:09:04.474 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorkotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2023-06-25 11:09:04.474 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorandroid.os.Handler.handleCallback(Handler.java:958)
2023-06-25 11:09:04.474 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorandroid.os.Handler.dispatchMessage(Handler.java:99)
2023-06-25 11:09:04.475 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorandroid.os.Looper.loopOnce(Looper.java:205)
2023-06-25 11:09:04.475 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorandroid.os.Looper.loop(Looper.java:294)
2023-06-25 11:09:04.475 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorandroid.app.ActivityThread.main(ActivityThread.java:8176)
2023-06-25 11:09:04.475 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorjava.lang.reflect.Method.invoke(Native Method)
2023-06-25 11:09:04.475 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorcom.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
2023-06-25 11:09:04.475 28218-28218 System.err              com.datatransexample                 W  ----------from onTransactionErrorcom.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`

**Comment by luiscosta** [comment]
Hello again @AmirSalahY,

Unfortunately, the stacktrace log you sent on your message is not the error we want to see.

Can you change your `onTransactionError` method to something like:
```
@Override
public void onTransactionError(@NonNull TransactionException e) {
    Log.e("error","onTransaction error", e);
}
```

This should give you the SDK error we want.

Thank you!

**Comment by bacherma** [comment]
@AmirSalahY any updates on this?

**Comment by bacherma** [comment]
Unclear status, likely misconfiguration. Closing the ticket.
