### ISSUE TITLE
The SDK cannot be downloaded from JFrog

### ISSUE THREAD

**Issue by eduardvasilache** [datatrans/android-sdk#14]
Hi,

We are getting the following error when building the project in our pipeline:

```
> Could not resolve ch.datatrans:android-sdk:3.1.1.
> Could not get resource 'https://datatrans.jfrog.io/artifactory/mobile-sdk/ch/datatrans/android-sdk/3.1.1/android-sdk-3.1.1.pom'.
> Could not GET 'https://landing.jfrog.com/reactivate-server/datatrans'. Received status code 409 from server: Conflict
```

The page https://datatrans.jfrog.io/artifactory/mobile-sdk is redirecting to https://landing.jfrog.com/reactivate-server/datatrans and is showing the following message: _"Enter the email used to register for the free JFrog subscription to reactivate the account"._

Everything was working fine until today.
Is this something that needs to be fixed on your side?

Thanks!

**Comment by Bresiu** [comment]
Hi,

Same is happening for us since yesterday evening.

**Comment by gtomek** [comment]
I also have this problem and I cannot use v2.7.0

You can see the following now if you click on the link: https://datatrans.jfrog.io/artifactory/mobile-sdk

```
JFrog's Free-Tier subscription has been deactivated.

The following options are available:

    Upgrade to a paid account by visiting [MyJFrog](https://my.jfrog.com/)
    For Java, Conan and Docker users, JFrog has free community or OSS editions available in our [developer downloads](https://jfrog.com/community/open-source/) area
    If you’re an [OSS contributor](https://jfrog.com/community/giving-back/), speaker or JFrog Guru, please [contact us](https://jfrog.com/contact-us/) to explore alternative paths for your projects
```

Any ideas when this will be sorted out?

**Comment by Bresiu** [comment]
@luiscosta Any update?

**Comment by Qoxis** [comment]
Hi,

We do have the same problem on our side:

09:27:18.662  > Could not resolve all files for configuration ':app:betaCompileClasspath'.
09:27:18.662     > Could not resolve ch.datatrans:android-sdk:3.1.0.
09:27:18.662       Required by:
09:27:18.662           project :app
09:27:18.662        > Could not resolve ch.datatrans:android-sdk:3.1.0.
09:27:18.662           > Could not parse POM https://datatrans.jfrog.io/artifactory/mobile-sdk/ch/datatrans/android-sdk/3.1.0/android-sdk-3.1.0.pom
09:27:18.662              > Already seen doctype.

**Comment by bacherma** [comment]
**Important update**: We apologize for the inconvenience caused. JFrog has deactivated standard accounts without notifying our current account admins, resulting in our loss of access. We are actively working to regain access but so far without success. As a (temporary) solution, we have set up a new repository that contains the latest releases.

**Please use the following repository URL**:

`https://weareplanet.jfrog.io/artifactory/mobile-sdk/`

As of now, this repository contains versions 2.7.0 - 3.1.1. The newest version 3.2.0 as well as older versions will be added later today. Thank you for your understanding.

**Comment by bacherma** [comment]
**Update:** 
The repository is back at: `https://datatrans.jfrog.io/artifactory/mobile-sdk/`

**Please update the URL, the temporary repo will stop working after Thursday 27th.**

Please accept our apologies for any inconvenience caused.

--
@Bresiu @gtomek @eduardvasilache @Qoxis @jschmid @DanielSobczak @CiprianU @jeremystucki @christianr-ifolor @rohlandm @Kevinrob

**Comment by Dzamir** [comment]
Thanks for the updates, but I can't find the 1.5.0 build on the updated repository: https://datatrans.jfrog.io/ui/native/mobile-sdk/ch/datatrans/android-sdk/
