### ISSUE TITLE
Swiss Francs wrong decimal separator

### ISSUE THREAD

**Issue by joost-klitsie** [datatrans/android-sdk#15]
For Swiss currencies, we expect them to be formatted like this:
#'###.##
However, if I select a Swiss German locale for my app, the currency is formatted as this:
#.###,##
I will attach a screen shot where in the top it is shown how we format it and how data trans is formatting it.
Because of the thousand grouping, it looks to me like the Swiss country is not being taken into account in the formatting.
![Screenshot_20230901_150646](https://github.com/datatrans/android-sdk/assets/42934802/2cf9375f-e0c0-487e-a3ee-260a43affb0e)

SDK version: 3.2.0

**Comment by luiscosta** [comment]
Hello @joost-klitsie,

We will look into it and fix it in the next release.

Thank you for raising the issue!

Best,

Luis

**Comment by joost-klitsie** [comment]
@luiscosta I see it is fixed in version 3.3.0 and it takes the locale of the app, thank you very much :) 
![correct_formatting](https://github.com/datatrans/android-sdk/assets/42934802/e77cbfc4-8c3d-44c5-864a-f5043e7f8079)
