### ISSUE TITLE
Failed to resolve: ch.datatrans:android-sdk:3.3.0

### ISSUE THREAD

**Issue by Jean-PhilippeDESCAMPS** [datatrans/android-sdk#17]
Hello,

I'm currently working to integrate your SDK in my project. 
I have follow your documentation at https://docs.pci-proxy.com/docs/mobile-sdks-quick-start#android
When I build project with gradle my project compiles correctly but I have a warning :
`Failed to resolve: ch.datatrans:android-sdk:3.3.0`
I used this url : 'https://datatrans.jfrog.io/artifactory/mobile-sdk/'

What's wrong with my integration ?

**Comment by luiscosta** [comment]
Hello,

As I have more than one project, I have something like this on my project's build.gradle: 

allprojects {
	repositories {
		(...)
		maven {
			setUrl("https://datatrans.jfrog.io/ui/native/mobile-sdk/")
		}
		(...)
	}
}

Additionally you can also declare it like: `maven(url = "https://datatrans.jfrog.io/ui/native/mobile-sdk/")`

Do you have something like this?

**Comment by luiscosta** [comment]
The maven of the Datatrans should be on something like:

```
buildscript {
    repositories {
        google()
    }

    dependencies {
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.42'
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.7.4"
    }
}

// OUTSIDE OF BUILDSCRIPT 
// UNDER THE MODULE REPOSITORIES
project(<path to your module>) {
	repositories {
		maven {
			setUrl("https://datatrans.jfrog.io/ui/native/mobile-sdk/")
		}
	}
}

// OR IF YOU HAVE MORE THAN ONE LIKE ME:

allProjects {
	repositories {
		maven {
			setUrl("https://datatrans.jfrog.io/ui/native/mobile-sdk/")
		}
	}
}


plugins {
    id 'com.android.application' version '8.0.0' apply false
    id 'com.android.library' version '8.0.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.0' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by luiscosta** [comment]
Perfect!!
