### ISSUE TITLE
[feature request] Scanning mastercard and visa debit cards with the scanner

### ISSUE THREAD

**Issue by andreaMOnline** [datatrans/android-sdk#18]
I noticed that on some devices the scanner does not work for the newer Mastercard debit cards. As a workaround (when Google Pay is set up) I can use the google pay card scanner though as a workaround.

The model I used (bad camera for close range): HMD Global Nokia 7.2., Android 11

**Comment by luiscosta** [comment]
Hello @andreaMOnline,

How do you use the Google Card Scanner? Is it on soft input autofill bar? 

Why is Google Scanner a workaround? That scanner is our recommended option if you use Google Pay with us. 

Best,

Luis

**Comment by andreaMOnline** [comment]
Hi Luis, unfortunately the later card models can not be recognized via the camera symbol in the datatrans UI. Eg Revolut prepaid cards (Visa) that I have. 
The Revolut Visa card has the card number written on the **back** of the card. When I turn it to the back and try to scan the number, it is not recognized by the datatrans scanner.

The google scanner is available via autofill bar yes. I think the problem is more iOS than Android because no workaround is available on iOS AFAIK

**Comment by bacherma** [comment]
Hi @andreaMOnline. I think there is some misunderstanding.

### On Android

The Google Scanner is not a workaround and we are not talking about the autofill bar. Our current solution is based on it when the SDK camera icon is pressed.

Whether you use Google Pay or not as a payment method does not matter. Please set up your app and [request production API access for Google Pay](https://developers.google.com/pay/api/android/guides/test-and-deploy/request-prod-access). You don't need to configure Google Pay on our side, support it in your backend or actually use Google Pay. But your app **must have access to the Google Pay API**.

### On iOS

We rewrote the iOS scanner from scratch a while ago. If you use a reasonably recent SDK version ([>= version 3.0.0](https://github.com/datatrans/ios-sdk/releases/tag/3.0.0)), your app automatically uses the new scanner that can perfectly read modern card designs such as Revolut's.

Does this answer your concerns?

**Comment by bacherma** [comment]
@andreaMOnline can I close this issue or do you have more questions?
