### ISSUE TITLE
Android: Camera permission issue

### ISSUE THREAD

**Issue by RaghavBOS** [datatrans/android-sdk#23]
If a user declines camera permission twice while using the credit card form (indicated by a photo icon), subsequent attempts to request permission won't trigger a popup prompting for camera access. do we have any solution to navigate to the Settings app to enable camera permission manually by clicking the photo icon button?

**Comment by bacherma** [comment]
Hi @RaghavBOS. This is an issue with the old card scanner which is no longer supported. Please set up your app to use the Google card scanner and [request Google Pay API access](https://developers.google.com/pay/api/android/guides/test-and-deploy/request-prod-access).
