### ISSUE TITLE
Credit Card Number entry field too small using OnePlus Font

### ISSUE THREAD

**Issue by pmatter** [datatrans/android-sdk#3]
On OnePlus Nord Device the credit card number entry field is too small when using the default OnePlus font. The last 2 digits of credit card number (16 digits) is not visible.

**Expected Behaviour:** Using the OnePlus font or any other the entry field should show all 16 digits of a credit card

Device Information:
OnePlus Nord AC2003
Android-Version: 12 (same issue on 11)
One Plus Font: Default
Datatrans SDK Version: 2.0.
![Datatrans](https://user-images.githubusercontent.com/35367833/177514083-5a75eae7-106e-42c9-b6ad-b95e0336c14f.jpeg)
![Schriftart](https://user-images.githubusercontent.com/35367833/177514108-9ddc6d30-fda7-4b54-b0d4-f225a68e46cb.jpeg)

**Comment by richiehug** [comment]
Hey @pmatter! We are looking into it. Will get back to you asap.

**Comment by pmatter** [comment]
Awesome, thanks a lot :-)
