### ISSUE TITLE
SDK has conflicting networkSecurityConfig

### ISSUE THREAD

**Issue by Charchad** [datatrans/android-sdk#8]
Hi,

Today we tried to upgrade from SDK version 2.1.0 to 2.3.3 but the project cannot be compiled because from version 2.2.0 you added a custom networkSecurityConfig which is conflicting with another configuration.

You shouldn't do this in a library, at least not in "release". If you want to customise the network config you should do it only for debug.

**Comment by BasilAch** [comment]
Fixed in [2.4.0](https://github.com/datatrans/android-sdk/releases/tag/2.4.0).

**Comment by Charchad** [comment]
Thanks!
